### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by sierrajulietromeo** [idunmore/CESIL#1]
Hey, just wanted to say I came across CESIL.org and your GitHub as you link to a scan I'm hosting - one of the ICL-CES Newsletters.  My interest is the History of Computing Education in England and I've managed to collect together various ICL-CES assets, including programs in CESIL, copies of the reference cards etc.  I should be able to get you further information on CESIL should you be interested!   Sorry for opening an Issue as I couldn't find another way to contact you as the links on CESIL.org at the bottom don't appear to work. I found a LinkedIn profile but wasn't sure if it was you!

**Comment by idunmore** [comment]
Hi Steve,

No worries about opening an issue, and thanks for reaching out and for the kind offer; I'll shoot you an email to discuss.

I've also setup valid email (etc.) links on CESIL.org, so you can reach me that way if you wish.  I'll close out this issue as a result.  And then I'll be adding more to the site, and removing the placeholder elements in the next day or so.

Thanks!
